# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM on release

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Configure Git identity
        run: |
          git config --global user.email "axolemaranjana4@gmail.com"
          git config --global user.name "Axole Maranjana"

      - name: Bump version
        run: npm version minor

      - name: Install dependencies
        run: npm install --no-frozen-lockfile --force && npm run lint

      - name: Clean Git working directory
        run: |
          git add . 
          git commit -m "chore: pre-release"

      - name: Publish to NPM
        run: npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
